/********************************************************************************************************
 * @file     UuidInfo.ets 
 *
 * @brief    for TLSR chips
 *
 * @author	 telink
 * @date     Sep. 30, 2010
 *
 * @par      Copyright (c) 2016, Telink Semiconductor (Shanghai) Co., Ltd.
 *           All rights reserved.
 *           
 *			 The information contained herein is confidential and proprietary property of Telink 
 * 		     Semiconductor (Shanghai) Co., Ltd. and is available under the terms 
 *			 of Commercial License Agreement between Telink Semiconductor (Shanghai) 
 *			 Co., Ltd. and the licensee in separate contract or the terms described here-in. 
 *           This heading MUST NOT be removed from this file.
 *
 * 			 Licensees are granted free, non-transferable use of the information in this 
 *			 file under Mutual Non-Disclosure Agreement. NO WARRENTY of ANY KIND is provided. 
 *           
 *******************************************************************************************************/
export const UUID_OTA_SERVICE = "00010203-0405-0607-0809-0A0B0C0D1912"

export const UUID_OTA_CHARACTERISTIC = "00010203-0405-0607-0809-0A0B0C0D2B12"

export const UUID_VERSION_SERVICE = "0000D0FF-3C17-D293-8E48-14FE2E4DA212"

export const UUID_VERSION_CHARACTERISTIC = "0000FFD4-0000-1000-8000-00805F9B34FB"

export const UUID_BATTERY_SERVICE = "0000180F-0000-1000-8000-00805F9B34FB"

export const UUID_BATTERY_LEVEL_CHARACTERISTIC = "00002A19-0000-1000-8000-00805F9B34FB"

export const UUID_CFG_DESCRIPTOR = "00002902-0000-1000-8000-00805F9B34FB"

// mesh
export const SERVICE_UUID_OTA = "00010203-0405-0607-0809-0A0B0C0D1912"

export const CHARACTERISTIC_UUID_OTA = "00010203-0405-0607-0809-0A0B0C0D2B12"

export const SERVICE_MESH_FLEX = "00007FDD-0000-1000-8000-00805F9B34FB"

export const SERVICE_PROVISION = "00001827-0000-1000-8000-00805F9B34FB"

export const CHARACTERISTIC_PB_IN = "00002ADB-0000-1000-8000-00805F9B34FB"

export const CHARACTERISTIC_PB_OUT = "00002ADC-0000-1000-8000-00805F9B34FB"

export const SERVICE_PROXY = "00001828-0000-1000-8000-00805F9B34FB"

export const CHARACTERISTIC_PROXY_IN = "00002ADD-0000-1000-8000-00805F9B34FB"

export const CHARACTERISTIC_PROXY_OUT = "00002ADE-0000-1000-8000-00805F9B34FB"

export const SERVICE_ONLINE_STATUS = "00010203-0405-0607-0809-0A0B0C0D1A10"

export const CHARACTERISTIC_ONLINE_STATUS = "00010203-0405-0607-0809-0A0B0C0D1A11"

export const DESCRIPTOR_CFG_UUID = "00002902-0000-1000-8000-00805F9B34FB"

export const SERVICE_DEVICE_INFO = "0000180A-0000-1000-8000-00805F9B34FB"

export const CHARACTERISTIC_FW_VERSION = "00002A26-0000-1000-8000-00805F9B34FB"
